//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicStudentDataV
    {
        public int stdid { get; set; }
        public string sname { get; set; }
        public int SeqID { get; set; }
        public string BirthPlace { get; set; }
        public string LastName { get; set; }
        public string gender { get; set; }
        public string natianalityt { get; set; }
        public string lvlState { get; set; }
        public string sgroup { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string Village { get; set; }
        public byte[] stdImage { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> DeletDate { get; set; }
        public Nullable<int> UserAdd { get; set; }
        public Nullable<int> UserEdit { get; set; }
        public Nullable<int> UserDelete { get; set; }
        public Nullable<int> courseLevelID { get; set; }
        public int courseid { get; set; }
        public string coursename { get; set; }
        public Nullable<double> deg1 { get; set; }
        public Nullable<double> deg2 { get; set; }
        public Nullable<double> deg3 { get; set; }
        public Nullable<double> deg4 { get; set; }
        public Nullable<double> forFull { get; set; }
        public double TotalAll { get; set; }
        public Nullable<int> termid { get; set; }
        public string termname { get; set; }
        public int levelid { get; set; }
        public string levelname { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int yearID { get; set; }
        public string studyYearEngl { get; set; }
        public Nullable<double> rnkTotal { get; set; }
        public int coursFialCount { get; set; }
        public int amontapsentcourse { get; set; }
        public string StudentRamk { get; set; }
        public string StudentRamkByLevel { get; set; }
        public Nullable<double> avgst { get; set; }
        public Nullable<int> curseCount { get; set; }
        public string ResultTxt { get; set; }
        public int genderNumber { get; set; }
        public bool IsLeave { get; set; }
    }
}
