//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeRank
    {
        public int ID { get; set; }
        public Nullable<double> FromGrade { get; set; }
        public Nullable<double> ToGrade { get; set; }
        public string RankName { get; set; }
    }
}
