//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureWeek
    {
        public int ID { get; set; }
        public Nullable<int> NumLecture { get; set; }
        public string LectureName { get; set; }
        public Nullable<System.DateTime> cDay { get; set; }
        public Nullable<int> CdayNum { get; set; }
        public Nullable<System.TimeSpan> fromdate { get; set; }
        public Nullable<System.TimeSpan> toDate { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> levelid { get; set; }
        public Nullable<int> termid { get; set; }
        public Nullable<int> IDRoom { get; set; }
        public Nullable<int> YearID { get; set; }
    
        public virtual course course { get; set; }
        public virtual level level { get; set; }
        public virtual studyYear studyYear { get; set; }
        public virtual term term { get; set; }
    }
}
