//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public level()
        {
            this.levels1 = new HashSet<level>();
            this.StudentAbsents = new HashSet<StudentAbsent>();
            this.studentdegrees = new HashSet<studentdegree>();
            this.StudentLevels = new HashSet<StudentLevel>();
            this.LectureWeeks = new HashSet<LectureWeek>();
            this.LevelCourses = new HashSet<LevelCourse>();
            this.RoomStudentInExams = new HashSet<RoomStudentInExam>();
            this.TableExams = new HashSet<TableExam>();
        }
    
        public int levelid { get; set; }
        public string levelname { get; set; }
        public Nullable<int> numbercourseterm1 { get; set; }
        public Nullable<int> nextLevelID { get; set; }
        public Nullable<bool> IsStop { get; set; }
        public Nullable<int> LevelTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<level> levels1 { get; set; }
        public virtual level level1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAbsent> StudentAbsents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentdegree> studentdegrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLevel> StudentLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureWeek> LectureWeeks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LevelCourse> LevelCourses { get; set; }
        public virtual TypeLevel TypeLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomStudentInExam> RoomStudentInExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableExam> TableExams { get; set; }
    }
}
