//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LevelCourse()
        {
            this.studentdegrees = new HashSet<studentdegree>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> termID { get; set; }
        public Nullable<double> maxDegree { get; set; }
        public Nullable<double> minDegree { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<double> DefaultDegree { get; set; }
        public Nullable<int> TermPlanID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> BredLevel { get; set; }
    
        public virtual course course { get; set; }
        public virtual level level { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual TermPlan TermPlan { get; set; }
        public virtual term term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentdegree> studentdegrees { get; set; }
    }
}
