//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageCategory()
        {
            this.Pages = new HashSet<Page>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletingUserID { get; set; }
        public Nullable<System.DateTime> DeletingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
    }
}
