//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageOperationRole
    {
        public int ID { get; set; }
        public Nullable<int> PageOperationID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> DeletingUserID { get; set; }
        public Nullable<System.DateTime> DeletingDate { get; set; }
    
        public virtual PageOperaion PageOperaion { get; set; }
        public virtual Role Role { get; set; }
    }
}
