//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.PageOperaions = new HashSet<PageOperaion>();
        }
    
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string PageTitle { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PageCategoryID { get; set; }
    
        public virtual PageCategory PageCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageOperaion> PageOperaions { get; set; }
    }
}
