//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageOperaion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageOperaion()
        {
            this.PageOperationRoles = new HashSet<PageOperationRole>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PageID { get; set; }
        public string OperationName { get; set; }
        public string OperationSymbol { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Page Page { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageOperationRole> PageOperationRoles { get; set; }
    }
}
