//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.TermPlans = new HashSet<TermPlan>();
            this.LevelCourses = new HashSet<LevelCourse>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Descript { get; set; }
        public Nullable<System.DateTime> sadte { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public Nullable<int> InstDeptSpecID { get; set; }
        public Nullable<int> YearID { get; set; }
    
        public virtual studyYear studyYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermPlan> TermPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LevelCourse> LevelCourses { get; set; }
    }
}
