//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomStudentInExam
    {
        public int ID { get; set; }
        public Nullable<int> StdID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> NumberPlace { get; set; }
        public Nullable<int> NumperPass { get; set; }
        public Nullable<int> PeriodID { get; set; }
    
        public virtual ExamPeriod ExamPeriod { get; set; }
        public virtual level level { get; set; }
        public virtual Room Room { get; set; }
        public virtual student student { get; set; }
        public virtual studyYear studyYear { get; set; }
        public virtual term term { get; set; }
    }
}
