//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class schoolData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public schoolData()
        {
            this.Users = new HashSet<User>();
        }
    
        public int seqid { get; set; }
        public string schoolName { get; set; }
        public string city { get; set; }
        public string gover { get; set; }
        public byte[] LogoImage { get; set; }
        public Nullable<int> AdminSchool { get; set; }
        public string Village { get; set; }
        public string HeaderExam { get; set; }
        public string AdminCity { get; set; }
        public string Appropriate { get; set; }
        public string DeptStatistical { get; set; }
        public string AdminGeneralGover { get; set; }
        public string AdminHeadExamGover { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
