//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAbsent
    {
        public int ID { get; set; }
        public Nullable<int> SID { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string Status { get; set; }
        public string CDay { get; set; }
        public Nullable<int> NumAbsent { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string IsFind { get; set; }
    
        public virtual student student { get; set; }
        public virtual level level { get; set; }
    }
}
