//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.StudentAbsents = new HashSet<StudentAbsent>();
            this.studentdegrees = new HashSet<studentdegree>();
            this.StudentLevels = new HashSet<StudentLevel>();
            this.RoomStudentInExams = new HashSet<RoomStudentInExam>();
        }
    
        public int ID { get; set; }
        public int SeqID { get; set; }
        public string sname { get; set; }
        public Nullable<int> levelid { get; set; }
        public string BirthPlace { get; set; }
        public string LastName { get; set; }
        public string gender { get; set; }
        public string natianalityt { get; set; }
        public Nullable<int> yearid { get; set; }
        public string lvlState { get; set; }
        public string sgroup { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public byte[] stdImage { get; set; }
        public string Village { get; set; }
        public Nullable<bool> IsLeave { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> DeletDate { get; set; }
        public Nullable<int> UserAdd { get; set; }
        public Nullable<int> UserEdit { get; set; }
        public Nullable<int> UserDelete { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual studyYear studyYear { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAbsent> StudentAbsents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentdegree> studentdegrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLevel> StudentLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomStudentInExam> RoomStudentInExams { get; set; }
    }
}
