//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLevel
    {
        public int ID { get; set; }
        public Nullable<int> StdID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<bool> active { get; set; }
        public string lvlState { get; set; }
        public string sgroup { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Note { get; set; }
    
        public virtual studyYear studyYear { get; set; }
        public virtual Group Group { get; set; }
        public virtual student student { get; set; }
        public virtual level level { get; set; }
    }
}
