//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentdegree
    {
        public int seqid { get; set; }
        public Nullable<int> studentid { get; set; }
        public Nullable<int> levelid { get; set; }
        public Nullable<int> courseLevelID { get; set; }
        public Nullable<int> courseID { get; set; }
        public Nullable<int> termid { get; set; }
        public Nullable<double> deg1 { get; set; }
        public Nullable<double> deg2 { get; set; }
        public double total { get; set; }
        public Nullable<double> deg3 { get; set; }
        public Nullable<double> deg4 { get; set; }
        public Nullable<double> forFull { get; set; }
        public double total2 { get; set; }
        public double TotalAll { get; set; }
        public Nullable<int> yearID { get; set; }
        public Nullable<int> amontapsentcourse { get; set; }
    
        public virtual studyYear studyYear { get; set; }
        public virtual term term { get; set; }
        public virtual student student { get; set; }
        public virtual level level { get; set; }
        public virtual LevelCourse LevelCourse { get; set; }
    }
}
