//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableExam
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string DayName { get; set; }
        public Nullable<int> DayNumber { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string CDateString { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<System.DateTime> ExamPeriodTime { get; set; }
    
        public virtual course course { get; set; }
        public virtual ExamPeriod ExamPeriod { get; set; }
        public virtual level level { get; set; }
        public virtual studyYear studyYear { get; set; }
        public virtual term term { get; set; }
    }
}
