//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotify
    {
        public int ID { get; set; }
        public string LectureName { get; set; }
        public Nullable<int> DayNum { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
    }
}
