//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.schoolDatas = new HashSet<schoolData>();
            this.ProfilePermanences = new HashSet<ProfilePermanence>();
            this.LevelCourses = new HashSet<LevelCourse>();
        }
    
        public int ID { get; set; }
        public string TeacherName { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Quali { get; set; }
        public string Experties { get; set; }
        public Nullable<System.DateTime> QualiDate { get; set; }
        public string QualiPlace { get; set; }
        public string Address { get; set; }
        public string TypeTeacher { get; set; }
        public Nullable<int> TypeTeacherID { get; set; }
        public Nullable<double> Rateb { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UserAdd { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> UserEdit { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> UserDelete { get; set; }
        public string IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schoolData> schoolDatas { get; set; }
        public virtual TypeTeatcher TypeTeatcher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilePermanence> ProfilePermanences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LevelCourse> LevelCourses { get; set; }
    }
}
